name: Evening Exercise

on:
  schedule:
    - cron: '00 12 * * 1-5'
  workflow_dispatch:

jobs:
  evening-exercise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Prepare environment
        run: pip install -r requirements.txt
      - name: Run app
        run: python main.py -r 38 -d 1200 -t 360 -q
        env:
          USER_ID: ${{ secrets.USER_ID }}
          FUDAN_SPORT_TOKEN: ${{ secrets.FUDAN_SPORT_TOKEN }}
          PLATFORM_OS: ${{ secrets.PLATFORM_OS }}
          PLATFORM_DEVICE: ${{ secrets.PLATFORM_DEVICE }}
